### PR TITLE
Added .htaccess and files for Heroku

### PR DESCRIPTION
**Pull request by ghostnegotiator**
Added missing .htaccess for modern Apache servers and included composer
and procfile for heroku deployment.

### CODE REVIEW

**Comment by RDash21** [comment]
Will add documentation later on in readme.md for heroku and normal web.

**Comment by wodim** [comment]
Please use a filename such as `INSTALL.md` for such purpose.

**Comment by RDash21** [comment]
Alright will do :+1:

**Comment by wodim** [comment]
I just made a commit that renders the Apache .htaccess file obsolete: from now on all URLs starting with `/static/` must be served by Apache itself, and the rest of them, by PHP.

**Comment by RDash21** [comment]
@wodim at the moment I am considering writing a QDB entirely in ZF2 (Maybe ZF3). And still reading up allot on it also had several features in mind which could be interesting for every one on IRC as Gaming related.

Although when I am more capable I would love to help you out and contribute more ;)

**Comment by wodim** [comment]
@RDash21 The rewrite is already in a pretty advanced state and I chose Flask (Python) to do it. My intention is to make it easy to deploy the code to Heroku easily and make it easily configurable, because the current PHP code is in a pretty bad state (I used this as an experiment to learn more about some coding practices.)

**Comment by RDash21** [comment]
Unfortunate I have no knowledge in Python even though I do got the books for it. Although I personally hope I can be of assistance in the near future. Although I have already made my repository for it and will open discussion probably next week on several forums.

Personally I love the concept and idea of Quotes Databases, but unfortunately not many people coders are working on it.

Although your Quote DB is the most updated and working nicely on PHP 5.4 as 5.6  ;)

**Comment by wodim** [comment]
Oh, sorry. I confused the Zend Framework with the Zope Framework, which is in Python. I read the `README.md` in your repo and I like your ideas, I think I'll borrow some of them.

I'm always open to suggestions and as long as they make sense I'm also open to implementing them. Unfortunately as I said this PHP codebase is really odd and I would rather start over with a framework which makes new features easier to implement.

**Comment by RDash21** [comment]
I totally agree on that it should make sense and all. Unfortunately I will have to revert back to PHP because ZF2 is too many steps ahead.  I am still learning in PHP and got a few people backing me up. Would it possible to ask you for help/feedback time to time?

Also I wondered if we could work in a unified way by contributing to each others with codes/feedback. Since my goal is pretty much to give people a solid support in their decision in hosting their own QDB.

Also its fine to steal my idea's and would love to see them implemented :)

**Comment by wodim** [comment]
I don't mind helping you with stuff, you can contact me at my email at any time.

**Pull request merged**
